
#ifndef __ERROR_H__
#define __ERROR_H__

typedef enum {
	ERR_DEVICE_NOT_FOUND,
	ERR_UNIT_NOT_FOUND,
	ERR_DEVICE_NOT_OPEN,
	ERR_CMD_NOT_SUPPORTED,
	ERR_IO_ABORTED,
	ERR_DEVICE_IN_USE,
	ERR_PERMISSION_DENIED
} Error_t;

#endif // __ERROR_H__
